// src/app/teacher/reports/page.tsx
'use client';

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { FileText, Download, Eye, Filter } from "lucide-react";
import Link from "next/link";

interface Report {
  id: string;
  studentName: string;
  classLevel: number;
  reportDate: string;
  overallGrade: string;
  generatedBy: string;
}

const mockReports: Report[] = [
  { id: "rep1", studentName: "Alex Johnson", classLevel: 5, reportDate: "2024-07-15", overallGrade: "B+", generatedBy: "Dr. Carter" },
  { id: "rep2", studentName: "Maria Garcia", classLevel: 5, reportDate: "2024-07-14", overallGrade: "A-", generatedBy: "Dr. Carter" },
  { id: "rep3", studentName: "David Lee", classLevel: 4, reportDate: "2024-07-15", overallGrade: "C+", generatedBy: "Mr. Davis" },
  { id: "rep4", studentName: "Sarah Miller", classLevel: 4, reportDate: "2024-07-13", overallGrade: "A", generatedBy: "Mr. Davis" },
  { id: "rep5", studentName: "Chen Wang", classLevel: 5, reportDate: "2024-07-15", overallGrade: "B", generatedBy: "Dr. Carter" },
];

export default function ViewReportsPage() {
  return (
    <div className="space-y-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold flex items-center"><FileText className="mr-3 text-primary" /> View Generated Reports</h1>
          <p className="text-muted-foreground">Access and manage all previously generated student report cards.</p>
        </div>
        <Link href="/teacher/report-card" passHref legacyBehavior>
          <Button size="lg" variant="outline">
            Generate New Report Card
          </Button>
        </Link>
      </div>

      <Card className="shadow-lg rounded-xl">
        <CardHeader>
          <div className="flex flex-col sm:flex-row justify-between items-center gap-2">
            <CardTitle>Report Archive</CardTitle>
            <Button variant="outline">
              <Filter className="mr-2 h-4 w-4" /> Filter Reports
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Student Name</TableHead>
                  <TableHead className="text-center">Class</TableHead>
                  <TableHead>Report Date</TableHead>
                  <TableHead className="text-center">Overall Grade</TableHead>
                  <TableHead className="hidden md:table-cell">Generated By</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {mockReports.map((report) => (
                  <TableRow key={report.id} className="hover:bg-muted/50">
                    <TableCell className="font-medium">{report.studentName}</TableCell>
                    <TableCell className="text-center">{report.classLevel}</TableCell>
                    <TableCell>{new Date(report.reportDate).toLocaleDateString()}</TableCell>
                    <TableCell className="text-center font-semibold">{report.overallGrade}</TableCell>
                    <TableCell className="hidden md:table-cell text-muted-foreground">{report.generatedBy}</TableCell>
                    <TableCell className="text-right space-x-2">
                      <Button variant="ghost" size="icon" title="View Report">
                        <Eye className="h-5 w-5 text-blue-500" />
                      </Button>
                      <Button variant="ghost" size="icon" title="Download Report">
                        <Download className="h-5 w-5 text-green-500" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
