
# Generated by Django 4.2.19 on YYYY-MM-DD HH:MM
# Replace YYYY-MM-DD HH:MM with the actual generation datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'), # Ensure this matches your previous migration name
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_and_students', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='admin_user',
            field=models.OneToOneField(blank=True, help_text='The primary admin user for this school, created during registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_school', to=settings.AUTH_USER_MODEL),
        ),
    ]
