# Generated by Django 4.2.19 on 2024-07-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0006_checkpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILessonQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Score as a percentage (0-100).')),
                ('passed', models.BooleanField(default=False)),
                ('quiz_data', models.JSONField(help_text="The AI-generated questions and the user's answers.")),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('can_reattempt_at', models.DateTimeField(blank=True, help_text='The earliest time the user can re-attempt the quiz.', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quiz_attempts', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'unique_together': {('user', 'lesson', 'attempted_at')},
            },
        ),
    ]
